// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	BaseResponse
	UserName string `json:"userName"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}
